name: HuntTeam Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
      - name: Test SSH Connection
        run: |
            ssh ${{ secrets.SSH_USER }}@${{ secrets.HOST }} "echo '✅ SSH подключение успешно!'"
      - name: Copy code to server
        run: |
          rsync -az --exclude ".git" --exclude "node_modules" -e "ssh -o StrictHostKeyChecking=no" ./ ${{ secrets.SSH_USER }}@${{ secrets.HOST }}:/home/${{ secrets.SSH_USER }}/huntteam

      - name: Write backend .env to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST }} << EOF
            echo "${{ secrets.BACKEND_ENV }}" > /home/${{ secrets.SSH_USER }}/huntteam/backend/.env
          EOF

      - name: Run docker-compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.HOST }} << 'EOF'
            cd ~/huntteam
            mkdir /backend/storage
            npm i dotenv
            docker-compose down
            docker-compose up --build
          EOF
